### ISSUE TITLE
Program doesnt seem to work anymore :(

### ISSUE THREAD

**Issue by glyko** [josueespinosa/BingBackground#1]
![bingbackground](https://cloud.githubusercontent.com/assets/16022594/11408002/95b07f4a-93b6-11e5-82ba-56c77a6e6e4e.PNG)

**Comment by josueespinosa** [comment]
The program still works; this appears to have been caused by an antivirus blocking that particular port for some reason. <a href="http://stackoverflow.com/questions/12692064/what-caused-the-socket-exception-while-sending-email-from-console-application" target="_blank">Check out this stackoverflow link for a possible solution.</a> However, I will add more detailed exception handling so in the future users can get clearer error messages.

**Comment by glyko** [comment]
Ok, after a bit of searching I found the cause of my issue: It was not caused by an Antivirus, but by this application called "DisableWinTracking" https://github.com/10se1ucgo/DisableWinTracking
It blocked the following IP, which is necessary for BingBackground to work via Windows firewall:
204.79.197.200
I just disabled the rule and now BingBackground works perfectly again.
I should have noticed this myself, sorry for bothering you.
Peace
